//
//  main.cpp
//  chapter16
//
//  Created by vividhsu on 7/30/15.
//  Copyright (c) 2015 Vividhsu. All rights reserved.
//

#include <iostream>
#include <vector>
#include <list>

#include "Sales_data.h"
#include "Blob.h"
#include "Screen.h"
#include "Vec.h"


using std::cout;
using std::endl;
using std::vector;
using std::list;

void ex16_01() {
    cout << "-----ex16.1-----" << endl;
    cout << "instantiation: class or function generated by the compiler from a template." << endl;
}

template <typename T>
int compare(const T& v1, const T& v2) {
    if (v1 < v2)
        return -1;
    if (v2 < v1)
        return 1;
    return 0;
}

void ex16_02() {
    cout << "-----ex16.2-----" << endl;
    cout << compare(3, 4) << endl;
    vector<int> v1{1, 2, 3};
    vector<int> v2{2, 3, 4};
    cout << compare(v1, v2);
}

void ex16_03() {
    cout << "-----ex16.3-----" << endl;
    Sales_data data1;
    Sales_data data2;
    //cout << compare(data1, data2);
    cout << "Invalid operands to binary expression (const Sales_data and const Sales_data) in line if (v1 < v2)" << endl;
}

template <typename Iterator, typename T>
Iterator myFind(Iterator first, Iterator last, const T& target) {
    while (first != last) {
        if (*first == target) {
            return first;
        }
        ++first;
    }
    return last;
}

void ex16_04() {
    cout << "-----ex16.4-----" << endl;
    vector<int> a{1, 2, 3, 4};
    auto it = myFind(a.begin(), a.end(), 3);
    cout << (it == a.end()) << endl;
    list<string> b{"a", "b", "c", "d"};
    auto it2 = myFind(b.begin(), b.end(), "e");
    cout << (it2 == b.end()) << endl;
}

template <typename T, unsigned N>
void myPrint(const T (&arr)[N]) {
    for (size_t i = 0; i != N; ++i) {
        cout << arr[i] << endl;
    }
}

void ex16_05() {
    cout << "-----ex16.5-----" << endl;
    string s[] = {"aa", "bb", "cc"};
    char c[] = {'a', 'b', 'c', 'd'};
    int  i[] = {1, 2, 3};
    myPrint(s);
    myPrint(c);
    myPrint(i);
}

template <typename T, size_t N>
T* myBegin(T (&arr)[N]) {
    T* iter = &arr[0];
    return iter;
}

template <typename T, size_t N>
T* myEnd(T (&arr)[N]) {
    T* iter = &arr[N - 1];
    iter++;
    return iter;
}


void ex16_06() {
    cout << "-----ex16.6-----" << endl;
    string s[] = {"aa", "bb", "cc" };
    char c[] = {'a', 'b', 'c', 'd'};
    int  i[] = {1, 2, 3};
    cout << *myBegin(s) << *(myEnd(s) - 1) << endl;
    cout << *myBegin(c) << *(myEnd(c) - 1) << endl;
    cout << *myBegin(i) << *(myEnd(i) - 1) << endl;
}

template <typename T, size_t N>
constexpr size_t mySize(const T (&arr)[N]) {
    return N;
}

void ex16_07() {
    cout << "-----ex16.7-----" << endl;
    string s[] = {"aa", "bb", "cc" };
    char c[] = {'a', 'b', 'c', 'd'};
    int  i[] = {1, 2, 3};
    cout << mySize(s) << endl;
    cout << mySize(c) << endl;
    cout << mySize(i) << endl;
}

void ex16_08() {
    cout << "-----ex16.8-----" << endl;
    cout << "all the container defines !=, easy to implement the template" << endl;
}

void ex16_09() {
    cout << "-----ex16.9-----" << endl;
    cout << "function template is a blueprint for generating functions. definition from which specific functions can be instantiated; \n";
    cout << "class template is a blueprint for generating classes. definition from which specific class can be instantiated" << endl;
}

void ex16_10() {
    cout << "-----ex16.10-----" << endl;
    cout << "when the compiler instantiates a class from template, it rewrites the class template, replacing each instance of the template parameter by the given template argument." << endl;
}

template <typename elemType> class ListItem;
template <typename elemType> class List {
public:
    List<elemType>();
    List<elemType>(const List<elemType>&);
    list<elemType>& operator=(const List<elemType>&);
    ~List();
    
    void insert(ListItem<elemType> *ptr, elemType value);

private:
    ListItem<elemType> *front, *end;
};

void ex16_11() {
    cout << "-----ex16.11-----" << endl;
    
}

void ex16_12() {
    cout << "-----ex16.12-----" << endl;
    Blob<int> a;
    a.push_back(1);
    a.push_back(2);
    cout << a.at(0) << endl;
    BlobPtr<int> ap(a);
    ap++;
    cout << *ap << endl;    
}

void ex16_13() {
    cout << "-----ex16.13-----" << endl;
    initializer_list<int> temp = {1, 2};
    Blob<int> a(temp);
    BlobPtr<int> ap(a);
    Blob<int> b(temp);
    BlobPtr<int> bp(a);
    cout << (ap == bp) << endl;
}

void ex16_14() {
    cout << "-----ex16.14-----" << endl;
    
}

void ex16_15() {
    cout << "-----ex16.15-----" << endl;
    Screen<5,5> scr('c');
    Screen<5,5> scr2;
    
    // output src to the screen
    std::cout<<scr;
    // input connet  to the  src
    std::cin>>scr2;
    // test input
    std::cout<<scr2;
}

void ex16_16() {
    cout << "-----ex16.16-----" << endl;
    Vec<int> vi;
    vi.push_back(1);
}


int main(int argc, const char * argv[]) {
//    ex16_01();
//    ex16_02();
//    ex16_03();
//    ex16_04();
//    ex16_05();
//    ex16_06();
//    ex16_07();
//    ex16_08();
//    ex16_09();
//    ex16_10();
//    ex16_11();
//    ex16_12();
//    ex16_13();
//    ex16_14();
//    ex16_15();
//    ex16_16();
    return 0;
}
